### ISSUE TITLE
Misleading heading in About page

### ISSUE THREAD

**Issue by Sopnil100** [gauravjk108/AnnapurnaHotelGroup3#12]
Assigned to: @np03a190015arjun

**Comment by np03a190015arjun** [comment]
Can you provide me the screenshot of the bug?

**Comment by Sopnil100** [comment]
![image](https://user-images.githubusercontent.com/81901457/118352377-db065a00-b580-11eb-9ad3-307dd3cd65f3.png)

The heading should not be 'Reviews' but should be "Testimonials'.

**Comment by np03a190015arjun** [comment]
![image](https://user-images.githubusercontent.com/81901298/118360023-8fb27280-b5a5-11eb-8d67-b0ece5171ebd.png)
The problem has been solved please check.

**Comment by Sopnil100** [comment]
I see the problems have been debugged. The issue is now closed. Thank you
