### ISSUE TITLE
Regarding proper design of Admin Login Page.

### ISSUE THREAD

**Issue by nandita55** [gauravjk108/AnnapurnaHotelGroup3#16]
![image](https://user-images.githubusercontent.com/81900964/118352339-adb9ac00-b580-11eb-87d1-4b02a59123fb.png)
Dear front and backend developers, I  liked the design of the Admin Login page a little less. Please enhance it more. Other pages are fine and you guys have done a really good job. But please work on that page with more enhancements.

**Comment by gauravjk108** [comment]
This issue was already created and closed. The login page has already been corrected.
