### ISSUE TITLE
Edit the form tag

### ISSUE THREAD

**Issue by aazadkhadka** [gauravjk108/AnnapurnaHotelGroup3#2]
### **The form tag needs to be enhanced.**
Enter a form action and method in the book.html file for backend purpose.

**Comment by gauravjk108** [comment]
Okay, it will be done in a minute. What actions do you want me to add to the tag?

**Comment by aazadkhadka** [comment]
add `<form action = login.php method = "POST">` inside your form tag. The backend will then function smoothly.

**Comment by gauravjk108** [comment]
Okay, the changes have been made and the code has been updated. Please check if the wanted changes were made. @aazadkhadka

**Comment by aazadkhadka** [comment]
Yes it's perfectly working now!
