### ISSUE TITLE
React JS incomaptibilty with external JS libraries

### ISSUE THREAD

**Issue by gauravjk108** [gauravjk108/AnnapurnaHotelGroup3#3]
I find it very complicated for ReactJS to work while using external libraries. Anyone have any suggestions regarding what we should do? Should be drop ReactJS altogether?

**Comment by aazadkhadka** [comment]
Since we are having problems integrating reactjs with django as well I agree that we should drop django and ReactJS and use vanilla HTML,CSS and JavaScript for frontend. I suggest using PHP for backend.

**Comment by gauravjk108** [comment]
Okay, I am fine with dropping both ReactJS and Django. I agree on using PHP since we are constraint with time.
