### ISSUE TITLE
Increase the quality of images

### ISSUE THREAD

**Issue by Sopnil100** [gauravjk108/AnnapurnaHotelGroup3#4]
Please increase the quality of images as the ones used were only of moderate quality.

**Comment by nandita55** [comment]
Also fix the appropriate pixel size of pictures.

**Comment by np03a190015arjun** [comment]
The pictures are stock photos and are placeholder. The actual image can be uploaded by the user through the admin dashboard after the completion of project. Or I can preload the pictures if necessary and provided.
