### ISSUE TITLE
Improve the content quality

### ISSUE THREAD

**Issue by Sopnil100** [gauravjk108/AnnapurnaHotelGroup3#5]
Please improve the quality of description. Also, include all the necessary details.

**Comment by nandita55** [comment]
Please focus on the necessary and applicable font size for letters.

**Comment by np03a190015arjun** [comment]
The font size have been optimized and checked for accessibility. Please be more specific about the changes you want to be made. The details are placeholder since we were not provided with any description by the client or the product manager. So, we have placed stock photos and description.
