### ISSUE TITLE
Ajust the  image size of the logo

### ISSUE THREAD

**Issue by aazadkhadka** [gauravjk108/AnnapurnaHotelGroup3#8]
The logo image we are trying to use doesn't fit the navigation bar properly. please edit the image size.

**Comment by np03a190015arjun** [comment]
The image size has been adjusted to fit inside the navigation bar. Please check it.

**Comment by gauravjk108** [comment]
The image size is good but I suggest to use text as a placeholder for now. We can definitely improve the quality of the logo.

**Comment by np03a190015arjun** [comment]
Okay, fine with me.
